name = "TestPackage"
uuid = "c8889301-ea7b-46cc-93c0-b5bb38d88a12"
authors = ["IlianPihlajamaa <ilian.pihlajamaa@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
LinearAlgebra = "1.11.0"
Plots = "1.41.1"
Random = "1.11.0"
